pipeline{
    agent any
    environment{
        SONAR_HOME= tool "sonar"
    }
    stages{
        stage("Code clone from Git"){
            steps{
                git url: "https://github.com/yathartha89/Wanderlust-app.git", branch: "main"
            }
        }
        stage("quality analysis with Sonar"){
            steps{
                withSonarQubeEnv("sonar"){
                    sh "$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=wanderlust -Dsonar.projectKey=wanderlust"
                }
            }
        }
        stage("OWASP Dependency Check"){
            steps{
                dependencyCheck additionalArguments: '--scan ./', odcInstallation: "DC"
                dependencyCheckPublisher pattern: "**/dependency-check-report.xml"
            }
        }
        stage("sonar quality gate scan"){
            steps{
                timeout(time: 2, unit: "MINUTES"){
                    waitForQualityGate abortPipeline: false
                }
            }
        }
        stage("Trivy scan file system"){
            steps{
                sh "trivy fs --format table -o trivy-fs-report.html ."
            }
        }
        stage("Deploy"){
            steps{
                sh "docker-compose up -d"
            }
        }
        
        
    }
    
    
}
